const randomIntegerInInterval = require("../src/random");

describe("generating random number", () => {
  test("generate a random number in interval 0 & 10", () => {
    const range = { min: 0, max: 10 };
    const random = 0.62;
    const randomTestFn = jest.fn(() => random);

    expect(randomIntegerInInterval(range, randomTestFn)).toBe(6);
  });

  test("checking minimum value generated by random interval function", () => {
    const range = { min: 5, max: 10 };
    const randomMin = 0 + 1e-18; // never zero is generated
    const randomTestFn = jest.fn(() => randomMin);

    expect(randomIntegerInInterval(range, randomTestFn)).toBe(range.min);
  });

  test("checking maximum value generated by random interval function is one less than max", () => {
    const range = { min: 5, max: 15 };
    const randomMax = 1 - 1e-18; // never one is generated
    const randomTestFn = jest.fn(() => randomMax);

    expect(randomIntegerInInterval(range, randomTestFn)).toBe(range.max);
  });
});
